run:
  go: '1.21'  # Use the Go version your project is using

linters:
  enable:
    - depguard
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - govet
    - unused
    - misspell
  disable:
    - errcheck

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: io/ioutil
            desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil