version: "2"
linters:
  enable:
    - misspell
    - unconvert
  disable:
    - errcheck
  settings:
    staticcheck:
      # Enable all options, with some exceptions.
      # For defaults, see https://golangci-lint.run/usage/linters/#staticcheck
      checks:
        - all
        - -QF1008     # Omit embedded fields from selector expression; https://staticcheck.dev/docs/checks/#QF1008
        - -ST1000     # TODO: Incorrect or missing package comment; https://staticcheck.dev/docs/checks/#ST1000
        - -ST1003     # Poorly chosen identifier; https://staticcheck.dev/docs/checks/#ST1003
formatters:
  enable:
    - gofmt
    - goimports
