name: Unit Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'

env:
  GOTOOLCHAIN: local

jobs:
  unit-test:
    name: Unit Test (${{ matrix.go-version || 'minimum' }})
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      matrix:
        go-version:
          - "" # empty; fall back on go-version-file (use go.mod); see https://github.com/actions/setup-go/issues/450#issuecomment-3620402646
          - 1.26
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 100

      - name: install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: "go.mod" # used when go-version is not specified.
          check-latest: true

      - name: unit test
        run: |
          sudo GO_TESTFLAGS=-v make test
